name:                bookie-api
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "bsherman (Brad Sherman)"
maintainer:          "bsherman (Brad Sherman)"
copyright:           "2020 Brad Sherman"

extra-source-files:
  - README.md
  - ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/bsherman/bookie>

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - GADTs
  - Arrows
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - TypeApplications
  - StandaloneDeriving
  - TypeSynonymInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables
  - DuplicateRecordFields
  - RankNTypes
  - LambdaCase
  - NamedFieldPuns


dependencies:
  - base
  - transformers
  - text
  - mtl
  - product-profunctors
  - postgresql-simple
  - postgresql-simple-url
  - resource-pool
  - time
  - monad-control
  - bytestring
  - scientific
  - exceptions
  - extra
  - aeson
  - opaleye
  - unordered-containers
  - morpheus-graphql
  - morpheus-graphql-core
  - scotty
  - envy
  - load-env
  - stm
  - jwt
  - containers
  - transformers-base
  - bcrypt
  - http-types
  - wai-cors


library:
  source-dirs: src

executables:
  web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wmissing-signatures
    dependencies:
      - bookie-api

tests:
  graphql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wmissing-signatures
    dependencies:
      - bookie-api
